# Generated by Django 5.2.12 on 2026-04-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0003_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="codemapping",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="codemapping",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="codemapping",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="codemapping",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="codemapping",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="datasourceconfig",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="datasourceconfig",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="datasourceconfig",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="datasourceconfig",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="datasourceconfig",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="ip",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="设备IP"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="displaycontentconfig",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="displaycontentconfig",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="displaycontentconfig",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="displaycontentconfig",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="displaycontentconfig",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="productionline",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="productionline",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="productionline",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="productionline",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="productionline",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
        migrations.AddField(
            model_name="screenconfig",
            name="reserved_1",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段1"
            ),
        ),
        migrations.AddField(
            model_name="screenconfig",
            name="reserved_2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段2"
            ),
        ),
        migrations.AddField(
            model_name="screenconfig",
            name="reserved_3",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段3"
            ),
        ),
        migrations.AddField(
            model_name="screenconfig",
            name="reserved_4",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段4"
            ),
        ),
        migrations.AddField(
            model_name="screenconfig",
            name="reserved_5",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="预留字段5"
            ),
        ),
    ]
