# Generated by Django 5.2.12 on 2026-04-17 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0004_area_reserved_1_area_reserved_2_area_reserved_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="backoffice.area",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="backoffice.productionline",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_lines",
                to="backoffice.area",
            ),
        ),
    ]
