# Generated by Django 5.2.12 on 2026-04-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_protect_area_line_deletes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserved_1",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段1"
                    ),
                ),
                (
                    "reserved_2",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段2"
                    ),
                ),
                (
                    "reserved_3",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段3"
                    ),
                ),
                (
                    "reserved_4",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段4"
                    ),
                ),
                (
                    "reserved_5",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段5"
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "specification",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserved_1",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段1"
                    ),
                ),
                (
                    "reserved_2",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段2"
                    ),
                ),
                (
                    "reserved_3",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段3"
                    ),
                ),
                (
                    "reserved_4",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段4"
                    ),
                ),
                (
                    "reserved_5",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段5"
                    ),
                ),
                ("order_no", models.CharField(max_length=64, unique=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "completed_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "计划"),
                            ("in_progress", "生产中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="backoffice.material",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="backoffice.productionline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "order_no"],
            },
        ),
        migrations.CreateModel(
            name="PageModuleSwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserved_1",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段1"
                    ),
                ),
                (
                    "reserved_2",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段2"
                    ),
                ),
                (
                    "reserved_3",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段3"
                    ),
                ),
                (
                    "reserved_4",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段4"
                    ),
                ),
                (
                    "reserved_5",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="预留字段5"
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(
                        choices=[("left", "左屏"), ("right", "右屏")], max_length=16
                    ),
                ),
                ("module_key", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["screen_key", "sort_order", "module_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("screen_key", "module_key"), name="uniq_screen_module"
                    )
                ],
            },
        ),
    ]
