# Generated by Django 4.2.29 on 2026-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0006_material_order_pagemoduleswitch"),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('healthy', 'healthy'), ('failed', 'failed')], default='healthy', max_length=16)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('fallback_in_use', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['source_key'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_key', models.CharField(max_length=32, unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('running_count', models.PositiveIntegerField(default=0)),
                ('abnormal_count', models.PositiveIntegerField(default=0)),
                ('status_breakdown', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['snapshot_key'],
            },
        ),
        migrations.CreateModel(
            name='EnergySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_key', models.CharField(max_length=32, unique=True)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='kWh', max_length=16)),
                ('area_summaries', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['snapshot_key'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_key', models.CharField(max_length=32, unique=True)),
                ('total_target_quantity', models.PositiveIntegerField(default=0)),
                ('total_produced_quantity', models.PositiveIntegerField(default=0)),
                ('overall_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_summaries', models.JSONField(blank=True, default=list)),
                ('trend_points', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['snapshot_key'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_key', models.CharField(max_length=32, unique=True)),
                ('line_schedules', models.JSONField(blank=True, default=list)),
                ('risk_summary', models.JSONField(blank=True, default=dict)),
                ('legend_items', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['snapshot_key'],
            },
        ),
    ]
